## Array Manipulation

## Array Manipulation - changing shape

In [2]:
import numpy as np

a = np.arange(9)
print('The original array:')
print(a)
print()

b=a.reshape(3,3)
print("the modified array:")
print(b) 

The original array:
[0 1 2 3 4 5 6 7 8]

the modified array:
[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [3]:
print(b.flatten())

[0 1 2 3 4 5 6 7 8]


In [4]:
b.flatten(order="F")

array([0, 3, 6, 1, 4, 7, 2, 5, 8])

In [11]:
b.flatten(order="c")
print(b)
b
# Return a copy of the array collapsed into one dimension.

[[0 1 2]
 [3 4 5]
 [6 7 8]]


array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [10]:
a = np.arange(12).reshape(4,3)
print(a)
a

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [12]:
np.transpose(a)

array([[ 0,  3,  6,  9],
       [ 1,  4,  7, 10],
       [ 2,  5,  8, 11]])

In [13]:
b = np.arange(8).reshape(2,4)
b

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [15]:
c = b.reshape(2,2,2)
# then we have two different groups of two variables of two dimensions.

In [16]:
np.rollaxis(c,2,1)

array([[[0, 2],
        [1, 3]],

       [[4, 6],
        [5, 7]]])

In [20]:
np.rollaxis(c,1)

array([[[0, 1],
        [4, 5]],

       [[2, 3],
        [6, 7]]])

In [22]:
np.swapaxes(c,1,2)

array([[[0, 2],
        [1, 3]],

       [[4, 6],
        [5, 7]]])

## Numpy Arithematic Operations

In [24]:
a = np.arange(9).reshape(3,3)
a

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [25]:
b = np.array([10,10,10])
b

array([10, 10, 10])